### ISSUE TITLE
Keep uppercase field names

### ISSUE THREAD

**Issue by chromadesign** [xpertbot/craft-wheelform#172]
Hi,

I'm currently setting up a form that submits both to the plugin and to Mailchimp via ajax . This would work fine except Mailchimp expects the field names to be all in uppercase. Unfortunately the plugin changes uppercase names to lowercase. Is there any way around this aside from a Javascript solution?

Best regards,
Manuela

**Comment by masiorama** [comment]
@chromadesign hello, I'm trying to do the same thing (send entry both to wheelform and mailchimp). I already set the form for wheelform, but still have no idea on how to send the data to mailchimp. Any suggestion? 
Thanks in andvance!

**Comment by chromadesign** [comment]
I have set up the form to submit via Javascript, one call to the wheelform url ("/wheelform/message/send") and one to the Mailchimp URL. This has worked fine once the field names weren't lowercased anymore.

**Comment by masiorama** [comment]
Thanks! What is the Mailchimp URL? The URL of the audience list? Is it enough to post that way?
I thought I had to use some mailchimp api js wrapper to send the data to mailchimp list, or something like that? 
I searched and found this https://github.com/thorning/node-mailchimp but still had no chance to test it.
Thanks!

**Comment by chromadesign** [comment]
The URL is the one Mailchimp provides for its own signup forms (you can find it in your audience under signup forms). But you need to change it slightly. The "post?u=" needs to be changed to "post-json?u=" and you need to add "&c=?" to the URL for it to make it work. My ajax call then looks like this (showing only the relevant part):

`$.ajax({
    type: 'GET',
    url: '<mailchimp url>',
    data: formData,
    cache: false,
    dataType: 'jsonp',
    jsonp: "c",
    contentType: 'application/json; charset=utf-8'
});`

**Comment by masiorama** [comment]
Thanks @chromadesign , much appreciated. Actually I was able to make it work with a slightly different approach, using a free mailchimp module for craft and than using its form action to handle authentication and data validation, passing data via ajax as you did. Cheers!
